### ISSUE TITLE
Cannot create binned data from numpy array

### ISSUE THREAD

**Issue by fchinu** [zfit/zfit#602]
## Current Behaviour
Creating binned data by passing a binned obs and an unbinned (numpy array) dataset causes the program to crash
```
import zfit 
import numpy as np

low, high = -5, 10
binning = zfit.binned.RegularBinning(15, low, high, name="obs") # Define the binning for the observable
obs = zfit.Space(obs='obs', binning=binning)                    # Create the observable space
obs_unbinned = zfit.Space('obs', low, high)                     # Create the observable space

size_normal = 10_000                                            # Set the size of the normal distribution data
data_normal_np = np.random.normal(size=size_normal, scale=2)    # Generate normal distribution data

data_normal = zfit.Data(data_normal_np, obs=obs)                # Create a zfit Data object with the normal distribution data
```
This program raises the error:
```
Traceback (most recent call last):
  File "/home/fchinu/Run3/B0_Analysis/Tests/zfit/zfit_issue.py", line 12, in <module>
    data_normal = zfit.Data(data_normal_np, obs=obs)                # Create a zfit Data object with the normal distribution data
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 105, in __call__
    obj = cls.from_numpy(array=data, obs=obs, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 750, in from_numpy
    return Data.from_tensor(  # *not* class, if subclass, keep constructor
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 832, in from_tensor
    return Data(
           ^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 97, in __call__
    obj.__init__(data, obs=obs, **kwargs)
  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 225, in __init__
    value, weights = check_cut_data_weights(limits=self.space, data=tensormap, weights=weights)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 1223, in check_cut_data_weights
    inside = limits.inside(data)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 896, in inside
    return self._inside(x, guarantee_limits)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 2183, in _inside
    x_inside = limit.inside(x_sub)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 556, in inside
    return self._inside(x, guarantee_limits)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 561, in _inside
    return inside_rect_limits(x, rect_limits=self._rect_limits_tf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/Repos/zfit/zfit/z/zextension.py", line 332, in concrete_func
    result = func_to_run(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fchinu/.virtualenv/ml312/lib/python3.12/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fchinu/.virtualenv/ml312/lib/python3.12/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tensorflow.python.framework.errors_impl.InternalError: Graph execution error:

Detected at node LogicalAnd defined at (most recent call last):
  File "/home/fchinu/Run3/B0_Analysis/Tests/zfit/zfit_issue.py", line 12, in <module>

  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 105, in __call__

  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 750, in from_numpy

  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 832, in from_tensor

  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 97, in __call__

  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 225, in __init__

  File "/home/fchinu/Repos/zfit/zfit/core/data.py", line 1223, in check_cut_data_weights

  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 896, in inside

  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 2183, in _inside

  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 556, in inside

  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 561, in _inside

  File "/home/fchinu/Repos/zfit/zfit/z/zextension.py", line 332, in concrete_func

  File "/home/fchinu/Repos/zfit/zfit/core/space.py", line 235, in inside_rect_limits

'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE'
         [[{{node LogicalAnd}}]] [Op:__inference_inside_rect_limits_44]
```

## Expected Behaviour
Expected to produce a `BinnedData` object (note that this bug was introduced lately: issue #579 was not raising any error when creating `BinnedData` in the same way)

## Context (Environment)
- zfit version: `develop` (`0.24.1.dev4+ga47396680`)
- Python version: `3.12.3`
- Are you using conda, pipenv, etc? : venv
- Operating System: `Ubuntu 24.04.1 LTS`
- Tensorflow version:`2.18.0`

**Comment by fchinu** [comment]
Very quick update: it seems to be related to the python version: running on python 3.11.10 prevents the program from crashing

**Comment by jonas-eschle** [comment]
Thanks a lot for reporting, and I've tried to reproduce it, but even with Python 3.12 I don't manage.
It seems somewhat related to the usage of a GPU, if you disable the GPU, i.e. by using 
```
    os.environ["CUDA_VISIBLE_DEVICES"] = (
        "-1"  # disable GPU, needs to be up here before any imports
    )
```
before the TF imports, does this work?

**Comment by ikrommyd** [comment]
Yeah I tried reproducing this with gpu as well (RTX 4080 SUPER) and it worked fine.

**Comment by jonas-eschle** [comment]
Great, thanks for checking and reporting! Closing (feel free to directly close in the future if an issue is resolved. If you close, we both can re-open, if I close, you can't)
